filter:
    excluded_paths: [tests/*]
build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'
checks:
    php: true
